image:
  file: .gitpod.Dockerfile

ports:
  - port: 4321
    onOpen: notify
    name: Astro Dev Server

tasks:
  - name: Setup
    before: |
      curl -fsSL https://bun.sh/install | bash
      echo 'export PATH="$HOME/.bun/bin:$PATH"' >> ~/.bashrc
      source ~/.bashrc
    init: |
      bun install
    command: |
      echo "🚀 Dev environment is ready!"
      echo "Run 'bun run dev' to start the Astro development server"

vscode:
  extensions:
    - astro-build.astro-vscode
    - bradlc.vscode-tailwindcss
    - ms-vscode.vscode-typescript-next
    - GitHub.copilot
    - GitHub.copilot-chat
    - esbenp.prettier-vscode
    - unifiedjs.vscode-mdx