name: Deploy to GitHub Pages

on:
  
  push:
    branches: [ main ] # Trigger the workflow every time you push to the `main` branch
  
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab on GitHub.

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install, build, and upload your site
        uses: withastro/action@e84f40bd8d2caa9e768ec82ad30dd81f0b280853 # v6.1.2
        with:
          # path: . # The root location of your Astro project inside the repository. (optional)
          node-version: 22 # The specific version of Node that should be used to build your site. Defaults to 20. (optional)
          package-manager: pnpm@11.24.0 # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)

  deploy:
    needs: build
    permissions:
      pages: write       # to deploy to Pages
      id-token: write    # to verify the deployment originates from an appropriate source
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: github-pages          
      - name: Display structure of downloaded files
        run: ls -R
      - name: Create dist directory
        run: mkdir -p ./dist
      - name: Extract artifact
        run: tar -xvf ./artifact.tar -C ./dist
      - name: Deploy to GitHub Pages on external repository
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: laurentkempe/techheadbrothers
          publish_branch: main
          publish_dir: dist