name: GenAI Spell Check

on:
  push:
    branches-ignore:
      - main
    paths:
      - '**/*.md'
      - '**/*.mdx'

permissions:
  contents: write
  models: read

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to compare with previous commit
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check if base commit exists
        id: check_base
        run: |
          if git rev-parse --quiet --verify "${{ github.event.before }}" >/dev/null; then
            echo "base_exists=true" >> $GITHUB_OUTPUT
            echo "base_commit=${{ github.event.before }}" >> $GITHUB_OUTPUT
          else
            echo "base_exists=false" >> $GITHUB_OUTPUT
            echo "base_commit=HEAD~1" >> $GITHUB_OUTPUT
          fi

      - name: Run GenAI spell check
        run: |
          npx --yes genaiscript run sc --vars base="${{ steps.check_base.outputs.base_commit }}"

      - name: Check for changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changed files:"
            git status --porcelain
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          fi

      - name: Commit and push changes
        if: steps.changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "fix: spellcheck markdown files [genai]"
          git push
